name 'evenup-thin'
version '0.2.3'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
project_page 'https://github.com/evenup/evenup-thin'
summary 'Manages thin'
description 'Installs thin and manages thin sites'
dependency 'evenup/ruby', '>= 1.3.4'
dependency 'evenup/apache', '>= 2.0.0'
